In [1]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

2025-06-28 13:38:43.476061: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-06-28 13:38:45.444671: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-28 13:38:45.444875: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-28 13:38:45.753570: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-28 13:38:46.526237: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-06-28 13:38:46.529106: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [11]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# define vocabulary
voc_size=10000

In [15]:
oen_hot_repr=[one_hot(words,voc_size)for words in sent]
oen_hot_repr

[[7488, 3123, 3866, 7265],
 [7488, 3123, 3866, 3677],
 [5887, 9126, 8274, 5933, 9496],
 [5887, 9126, 8274, 5933, 8669],
 [6720, 7488, 8278, 3866, 177],
 [9431, 4019, 9322, 5933]]

In [18]:
## word embedding repr
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [23]:
sent_length=8
embedded_docs=pad_sequences(oen_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7488 3123 3866 7265]
 [   0    0    0    0 7488 3123 3866 3677]
 [   0    0    0 5887 9126 8274 5933 9496]
 [   0    0    0 5887 9126 8274 5933 8669]
 [   0    0    0 6720 7488 8278 3866  177]
 [   0    0    0    0 9431 4019 9322 5933]]


In [24]:
dim=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-06-28 01:25:55.626178: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 33ms/step


array([[ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 1.2375522e-02,  4.5247186e-02, -2.4707174e-02,  3.0074827e-03,
         4.0754203e-02, -3.2057278e-03, -3.9506353e-02, -2.4354769e-02,
         4.3051247e-02,  1.6359273e-02],
       [ 3.2459367e-02, -4.6896663e-02, -3.2483473e-02,  5.9986115e-03,
   

In [36]:
model.predict(embedded_docs[1])

1/1 [==============================] - 0s 36ms/step


array([[ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 2.0508979e-02,  2.9581103e-02,  2.7565729e-02, -3.3036031e-02,
         3.3423528e-03,  3.6168210e-03,  2.6815820e-02, -1.0698535e-02,
         2.5810007e-02, -3.4632098e-02],
       [ 1.2375522e-02,  4.5247186e-02, -2.4707174e-02,  3.0074827e-03,
         4.0754203e-02, -3.2057278e-03, -3.9506353e-02, -2.4354769e-02,
         4.3051247e-02,  1.6359273e-02],
       [ 3.2459367e-02, -4.6896663e-02, -3.2483473e-02,  5.9986115e-03,
   